### ISSUE TITLE
Include terminfo files on hosts with sshd

### ISSUE THREAD

**Issue by m-wynn** [collegiumv/cv_config#20]
This way people with all kinds of $TERM's can use the terminal.  This should be part of the sshd role.

**Comment by the-maldridge** [comment]
I have noticed that my bashrc is also not generally loaded when I ssh in, do you believe this could be related to that issue, or is this specifically fixing a rendering issue?

**Comment by m-wynn** [comment]
I do not think this is related.

**Comment by m-wynn** [comment]
This was fixed in 8fc4f1d was it not?
